#![feature(inner_deref)]

[package]
name = "importer"
version = "0.1.0"
authors = ["Ollie Nye <ollie@nyemail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.9.2"
bson = "0.14.1"
csv = "1"
